// GENERATED by examples/self-deliver — do not edit by hand.
// Excluded from the candidate digest (see src/ports/digest.mjs) so writing the
// receipt never changes the identity it describes.

export type Receipt = {
  candidate: string;
  darkUrl: string | null;
  evidence: string;
  admitted: boolean;
  promotedToProd: boolean;
  verifier: string;
  policy: string;
  signature: string;
  builtAt: string;
  status: string;
};

export const receipt: Receipt = {
  "candidate": "sha256:6ed0e0046c5a91f0fdafea3c0cdf7044729f6f527d343fae2d654f0e39260cce",
  "darkUrl": "https://new-sdlc-dark-6ed0e0046c5a91f0fdafea3c.cloudflare-support-chat.workers.dev",
  "evidence": "home-200=pass,docs-200=pass",
  "admitted": true,
  "promotedToProd": false,
  "verifier": "2c0ef5ed13765683",
  "policy": "new-sdlc/self-deliver-fanout@1",
  "signature": "mg0czIobZRGHgmARh2XPrMVFG8PkVj5LGLjqmSwtbfblZl2JZbXN9GNphkiSotfdpaOpWiaWMaEhVb4ay/MOBA==",
  "builtAt": "2026-06-29T22:49:29.399Z",
  "status": "admitted by keel — awaiting owner promotion to new-sdlc.coey.dev"
};
