// GENERATED by examples/self-deliver — do not edit by hand.
// Excluded from the candidate digest (see src/ports/digest.mjs) so writing the
// receipt never changes the identity it describes.

export type Receipt = {
  candidate: string;
  darkUrl: string | null;
  evidence: string;
  admitted: boolean;
  promotedToProd: boolean;
  verifier: string;
  policy: string;
  signature: string;
  builtAt: string;
  status: string;
};

export const receipt: Receipt = {
  "candidate": "sha256:e7ab3959eb089c63cbb0672077a23ea2f5dbc081c23458a4ecaf6852342f390f",
  "darkUrl": "https://airlock-dark-e7ab3959eb089c63cbb06720.coy.workers.dev",
  "evidence": "home-200=pass,docs-200=pass",
  "admitted": true,
  "promotedToProd": true,
  "verifier": "2c0ef5ed13765683",
  "policy": "airlock/self-deliver-fanout@1",
  "signature": "m5pKKZvwU51qTZUtXioibQWjsFK3XdcR0XUTZjxJ0xKLVrLS7er3WRtvIo8xChEw7sf9HlbG3Isqt4MCYSBJCA==",
  "builtAt": "2026-06-30T15:41:25.002Z",
  "status": "promoted to airlock.coey.dev by owner — proof verified, gate ON"
};
