// self-deliver: run THIS repo through its own pipeline on a Cloudflare preview Worker.
//
//   compute candidate digest (content-addressed source)
//     -> embed it in the site (receipt the page will carry)
//     -> build
//     -> deploy to a preview URL with no live traffic
//     -> fanout^x tests on terrarium against the preview URL
//     -> keel admits a signed proof bound to the exact digest
//     -> record the promotion REQUEST (prod flip is human-gated; we STOP)
//     -> re-embed the full receipt + redeploy the same preview Worker
//     -> write RECEIPT.json
//
// This does NOT promote to airlock.coey.dev. Promotion is owner-held. The
// honesty gate (experiments/dogfood/gate.mjs) verifies everything by LOOKING.

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { runPipeline, type Ports, type TestJob } from "../../src/pipeline.ts";
import {
  candidateDigest,
  loadVerifier,
  makeDeployer,
  makeHumanGate,
  makeSigner,
  makeTerrariumFanout,
  type FanoutJob,
} from "../../src/ports/index.ts";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "../..");

// No machine-specific defaults: self-deliver deploys to a real Cloudflare
// account and shells out to a local terra CLI, so both must be provided
// explicitly. Fail loudly rather than silently targeting someone else's account
// or a path that only exists on one developer's machine.
function requireEnv(name: string, hint: string): string {
  const v = process.env[name];
  if (!v) {
    console.error(
      `self-deliver: missing required env ${name}.\n  ${hint}\n` +
        `  See README "Reproduce the dogfood" for the full list.`,
    );
    process.exit(2);
  }
  return v;
}

const ACCOUNT_ID = requireEnv(
  "CLOUDFLARE_ACCOUNT_ID",
  "export CLOUDFLARE_ACCOUNT_ID=<your Cloudflare account id> (the preview Worker deploys here)",
);
const TERRA_CLI = requireEnv(
  "TERRA_CLI",
  "export TERRA_CLI=/path/to/terrarium/src/cli.js (the fanout backend)",
);
const TERRA_MODEL = process.env.TERRA_MODEL; // optional; terra picks a default

function sh(bin: string, args: string[], cwd: string, env: NodeJS.ProcessEnv = {}) {
  return execFileSync(bin, args, {
    cwd,
    encoding: "utf8",
    stdio: ["ignore", "inherit", "inherit"],
    env: { ...process.env, ...env },
    maxBuffer: 64 * 1024 * 1024,
  });
}

type ReceiptShape = {
  candidate: string;
  previewUrl: string | null;
  evidence: string;
  admitted: boolean;
  promotedToProd: boolean;
  verifier: string;
  policy: string;
  signature: string;
  builtAt: string;
  status: string;
};

function writeReceipt(r: ReceiptShape) {
  // Self-contained so it carries no extra imports into the digest-excluded file.
  const body = `// GENERATED by examples/self-deliver — do not edit by hand.
// Excluded from the candidate digest (see src/ports/digest.mjs) so writing the
// receipt never changes the identity it describes.

export type Receipt = {
  candidate: string;
  previewUrl: string | null;
  evidence: string;
  admitted: boolean;
  promotedToProd: boolean;
  verifier: string;
  policy: string;
  signature: string;
  builtAt: string;
  status: string;
};

export const receipt: Receipt = ${JSON.stringify(r, null, 2)};
`;
  writeFileSync(join(REPO_ROOT, "site/src/lib/receipt.ts"), body);
}

function buildSite() {
  sh(
    join(REPO_ROOT, "site/node_modules/.bin/vite"),
    ["build"],
    join(REPO_ROOT, "site"),
    { NODE_ENV: "production" },
  );
}

async function main() {
  const candidate = candidateDigest(REPO_ROOT);
  console.log(`candidate digest : ${candidate}`);
  console.log(`account          : ${ACCOUNT_ID}`);

  const { verifier, trusted, source } = loadVerifier(REPO_ROOT);
  console.log(`verifier key     : ${verifier.keyId} (${source})`);

  // phase 1: embed the digest so the preview Worker carries its own identity
  const builtAt = new Date().toISOString();
  writeReceipt({
    candidate,
    previewUrl: null,
    evidence: "pending",
    admitted: false,
    promotedToProd: false,
    verifier: verifier.keyId,
    policy: "airlock/self-deliver-fanout@1",
    signature: "",
    builtAt,
    status: "candidate deployed for verification",
  });
  console.log("build            : phase 1 (identity embedded)…");
  buildSite();

  const deploy = makeDeployer({ repoRoot: REPO_ROOT, accountId: ACCOUNT_ID });
  let slotUrl: string | undefined;
  // Guard against TOCTOU: writing the receipt + building must NOT change any
  // digest-relevant source. Re-assert the candidate identity right before every
  // deploy, so the bytes we ship always match the digest we signed/embedded.
  const assertStableDigest = (c: string) => {
    const now = candidateDigest(REPO_ROOT);
    if (now !== c) {
      console.error(
        `self-deliver: candidate digest drifted during the run.\n` +
          `  expected ${c}\n  now      ${now}\n` +
          `  a digest-relevant source file changed mid-flight; refusing to deploy.`,
      );
      process.exit(3);
    }
  };
  const ports: Ports = {
    deploy: async (c) => {
      assertStableDigest(candidate);
      const slot = await deploy(c);
      slotUrl = slot.url;
      console.log(`preview deploy   : ${slot.url} (${slot.detail ?? ""})`);
      return slot;
    },
    runFanout: makeTerrariumFanout({
      terraBin: TERRA_CLI,
      cwd: REPO_ROOT,
      model: TERRA_MODEL,
      timeoutMs: 220_000,
    }),
    sign: makeSigner(verifier),
    setFeatureGate: makeHumanGate({ repoRoot: REPO_ROOT, previewUrl: () => slotUrl }),
    trusted,
  };

  // fanout: terrarium route probes that each fetch the preview URL and confirm the
  // route is 200 AND the served body carries the exact candidate digest. Every
  // job is a real observation of the deployed slot — no tautological in-process
  // jobs that merely restate a value we already hold.
  const jobs: (TestJob | FanoutJob)[] = [
    { name: "home-200", backend: "terra", route: "/", marker: candidate } as FanoutJob,
    { name: "docs-200", backend: "terra", route: "/docs", marker: candidate } as FanoutJob,
  ];

  console.log("fanout^x         : terrarium child runs against the preview URL…");
  const receipt = await runPipeline(
    { repo: "airlock", candidate },
    jobs as TestJob[],
    ports,
  );

  console.log(`fanout results   : ${receipt.evidence}`);
  console.log(`keel admitted    : ${receipt.admitted} (${receipt.reason})`);

  if (!receipt.admitted) {
    console.error("NOT ADMITTED — leaving the preview Worker up, not promoting. STOP.");
    writeReceiptArtifact(receipt, verifier, candidate, slotUrl ?? null, false);
    process.exit(1);
  }

  // phase 2: re-embed the full, signed receipt and redeploy the SAME preview Worker
  // so the served page shows the real receipt for the digest it serves.
  writeReceipt({
    candidate,
    previewUrl: receipt.slot.url,
    evidence: receipt.evidence,
    admitted: true,
    promotedToProd: false,
    verifier: verifier.keyId,
    policy: receipt.proof.proof.policy,
    signature: receipt.proof.signature,
    builtAt,
    status: "admitted by keel — awaiting owner promotion to airlock.coey.dev",
  });
  console.log("build            : phase 2 (full receipt embedded)…");
  buildSite();
  assertStableDigest(candidate);
  const finalSlot = await deploy(candidate);
  console.log(`preview redeploy : ${finalSlot.url}`);

  writeReceiptArtifact(receipt, verifier, candidate, finalSlot.url, true);

  console.log("\n=== STOP: candidate verified, prod gate human-held ===");
  console.log(`preview URL: ${finalSlot.url}`);
  console.log(`digest     : ${candidate}`);
  console.log(`proof      : ${verifier.keyId} ${receipt.proof.signature.slice(0, 24)}…`);
  console.log("next       : run experiments/dogfood/gate.mjs to verify by looking.");
}

function writeReceiptArtifact(
  receipt: Awaited<ReturnType<typeof runPipeline>>,
  verifier: { keyId: string; publicPem: string },
  candidate: string,
  previewUrl: string | null,
  admitted: boolean,
) {
  const artifact = {
    candidate,
    previewUrl,
    admitted,
    promotedToProd: false,
    promotion: {
      state: "awaiting-owner",
      target: "airlock.coey.dev",
      note: "Promotion is the owner-held, keel-gated step. Not performed by this loop.",
    },
    evidence: receipt.evidence,
    results: receipt.results,
    reason: receipt.reason,
    proof: receipt.proof,
    // Carried for convenience/inspection only. The honesty gate does NOT trust
    // this keyring; it verifies against the PINNED public key committed at
    // experiments/dogfood/trusted-keys.json.
    trusted: { [verifier.keyId]: verifier.publicPem },
    coverage: {
      "what-this-dogfood-proves":
        "source content-address (digest) + ed25519 signed admission proof bound to it + real preview Worker deploy + both routes served 200 carrying the digest. Verified by experiments/dogfood/gate.mjs against a pinned key.",
      "served-ref-cas":
        "the promote/CAS feature-gate flip is exercised by src/napkin.test.ts (local file-backed), NOT end-to-end in this dogfood run; prod promotion is the owner-held keel step.",
      "digest-scope":
        "the digest is a content address of the SOURCE tree, not a hash of the deployed Worker bytes (the page embeds its own signed receipt and cannot hash itself).",
    },
    generatedAt: new Date().toISOString(),
  };
  writeFileSync(
    join(REPO_ROOT, "experiments/dogfood/RECEIPT.json"),
    JSON.stringify(artifact, null, 2),
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
