// self-deliver: run THIS repo through its own pipeline to a DARK Cloudflare slot.
//
//   compute candidate digest (content-addressed source)
//     -> embed it in the site (receipt the page will carry)
//     -> build
//     -> deploy to a non-serving slot (dark URL)
//     -> fanout^x tests on terrarium against the dark URL
//     -> keel admits a signed proof bound to the exact digest
//     -> record the promotion REQUEST (prod flip is human-gated; we STOP)
//     -> re-embed the full receipt + redeploy the same dark slot
//     -> write RECEIPT.json
//
// This does NOT promote to new-sdlc.coey.dev. Promotion is owner-held. The
// honesty gate (experiments/dogfood/gate.mjs) verifies everything by LOOKING.

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { runPipeline, type Ports, type TestJob } from "../../src/pipeline.ts";
import {
  candidateDigest,
  loadVerifier,
  makeDeployer,
  makeHumanGate,
  makeSigner,
  makeTerrariumFanout,
  type FanoutJob,
} from "../../src/ports/index.ts";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "../..");
const ACCOUNT_ID =
  process.env.CLOUDFLARE_ACCOUNT_ID ?? "31b91e7f9954ad8aa334d46f012bd8ed";
const TERRA_CLI =
  process.env.TERRA_CLI ?? "/Users/jcoeyman/cloudflare/terrarium/src/cli.js";
const TERRA_MODEL = process.env.TERRA_MODEL; // optional; terra picks a default

function sh(bin: string, args: string[], cwd: string, env: NodeJS.ProcessEnv = {}) {
  return execFileSync(bin, args, {
    cwd,
    encoding: "utf8",
    stdio: ["ignore", "inherit", "inherit"],
    env: { ...process.env, ...env },
    maxBuffer: 64 * 1024 * 1024,
  });
}

type ReceiptShape = {
  candidate: string;
  darkUrl: string | null;
  evidence: string;
  admitted: boolean;
  promotedToProd: boolean;
  verifier: string;
  policy: string;
  signature: string;
  builtAt: string;
  status: string;
};

function writeReceipt(r: ReceiptShape) {
  // Self-contained so it carries no extra imports into the digest-excluded file.
  const body = `// GENERATED by examples/self-deliver — do not edit by hand.
// Excluded from the candidate digest (see src/ports/digest.mjs) so writing the
// receipt never changes the identity it describes.

export type Receipt = {
  candidate: string;
  darkUrl: string | null;
  evidence: string;
  admitted: boolean;
  promotedToProd: boolean;
  verifier: string;
  policy: string;
  signature: string;
  builtAt: string;
  status: string;
};

export const receipt: Receipt = ${JSON.stringify(r, null, 2)};
`;
  writeFileSync(join(REPO_ROOT, "site/src/lib/receipt.ts"), body);
}

function buildSite() {
  sh(
    join(REPO_ROOT, "site/node_modules/.bin/vite"),
    ["build"],
    join(REPO_ROOT, "site"),
    { NODE_ENV: "production" },
  );
}

async function main() {
  const candidate = candidateDigest(REPO_ROOT);
  console.log(`candidate digest : ${candidate}`);
  console.log(`account          : ${ACCOUNT_ID}`);

  const { verifier, trusted, source } = loadVerifier(REPO_ROOT);
  console.log(`verifier key     : ${verifier.keyId} (${source})`);

  // phase 1: embed the digest so the dark slot carries its own identity
  const builtAt = new Date().toISOString();
  writeReceipt({
    candidate,
    darkUrl: null,
    evidence: "pending",
    admitted: false,
    promotedToProd: false,
    verifier: verifier.keyId,
    policy: "new-sdlc/self-deliver-fanout@1",
    signature: "",
    builtAt,
    status: "dark candidate — verification in progress",
  });
  console.log("build            : phase 1 (identity embedded)…");
  buildSite();

  const deploy = makeDeployer({ repoRoot: REPO_ROOT, accountId: ACCOUNT_ID });
  let slotUrl: string | undefined;
  const ports: Ports = {
    deploy: async (c) => {
      const slot = await deploy(c);
      slotUrl = slot.url;
      console.log(`dark deploy      : ${slot.url} (${slot.detail ?? ""})`);
      return slot;
    },
    runFanout: makeTerrariumFanout({
      terraBin: TERRA_CLI,
      cwd: REPO_ROOT,
      model: TERRA_MODEL,
      timeoutMs: 220_000,
    }),
    sign: makeSigner(verifier),
    setFeatureGate: makeHumanGate({ repoRoot: REPO_ROOT, darkUrl: () => slotUrl }),
    trusted,
  };

  // fanout: terrarium route probes against the dark slot + an in-process unit job
  const jobs: (TestJob | FanoutJob)[] = [
    { name: "home-200", backend: "terra", route: "/", marker: candidate } as FanoutJob,
    { name: "docs-200", backend: "terra", route: "/docs" } as FanoutJob,
    {
      name: "digest-embedded",
      run: () => ({
        name: "digest-embedded",
        ok: candidate.startsWith("sha256:"),
        detail: candidate,
      }),
    },
  ];

  console.log("fanout^x         : terrarium child runs against the dark slot…");
  const receipt = await runPipeline(
    { repo: "new-sdlc", candidate },
    jobs as TestJob[],
    ports,
  );

  console.log(`fanout results   : ${receipt.evidence}`);
  console.log(`keel admitted    : ${receipt.admitted} (${receipt.reason})`);

  if (!receipt.admitted) {
    console.error("NOT ADMITTED — leaving the dark slot up, not promoting. STOP.");
    writeReceiptArtifact(receipt, verifier, candidate, slotUrl ?? null, false);
    process.exit(1);
  }

  // phase 2: re-embed the full, signed receipt and redeploy the SAME dark slot
  // so the served page shows the real receipt for the digest it serves.
  writeReceipt({
    candidate,
    darkUrl: receipt.slot.url,
    evidence: receipt.evidence,
    admitted: true,
    promotedToProd: false,
    verifier: verifier.keyId,
    policy: receipt.proof.proof.policy,
    signature: receipt.proof.signature,
    builtAt,
    status: "admitted by keel — awaiting owner promotion to new-sdlc.coey.dev",
  });
  console.log("build            : phase 2 (full receipt embedded)…");
  buildSite();
  const finalSlot = await deploy(candidate);
  console.log(`dark redeploy    : ${finalSlot.url}`);

  writeReceiptArtifact(receipt, verifier, candidate, finalSlot.url, true);

  console.log("\n=== STOP: dark candidate admitted, prod gate human-held ===");
  console.log(`dark URL   : ${finalSlot.url}`);
  console.log(`digest     : ${candidate}`);
  console.log(`proof      : ${verifier.keyId} ${receipt.proof.signature.slice(0, 24)}…`);
  console.log("next       : run experiments/dogfood/gate.mjs to verify by looking.");
}

function writeReceiptArtifact(
  receipt: Awaited<ReturnType<typeof runPipeline>>,
  verifier: { keyId: string; publicPem: string },
  candidate: string,
  darkUrl: string | null,
  admitted: boolean,
) {
  const artifact = {
    candidate,
    darkUrl,
    admitted,
    promotedToProd: false,
    promotion: {
      state: "awaiting-owner",
      target: "new-sdlc.coey.dev",
      note: "Promotion is the owner-held, keel-gated step. Not performed by this loop.",
    },
    evidence: receipt.evidence,
    results: receipt.results,
    reason: receipt.reason,
    proof: receipt.proof,
    trusted: { [verifier.keyId]: verifier.publicPem },
    generatedAt: new Date().toISOString(),
  };
  writeFileSync(
    join(REPO_ROOT, "experiments/dogfood/RECEIPT.json"),
    JSON.stringify(artifact, null, 2),
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
